language: node_js
node_js:
- 6.4.0
deploy:
  api_key:
    secure: sKYuZaSftOrxNN7dLN/JRDIKs4syIMR6ItbAJhX06R88WQwBm06/jNYLzZpHk8lY4X2HwdFrqAvQn3LGVhIyWGPyLLVR3ZM65H4An50vnWZOj0E88YdTpkJ73T0evj1/ZHH49JMz3ArLXl6Z0o2C7+4AtyyBdLtdGMUiaR9kpl5u/MQBunQsoDcCDLtoKYT5VUtLfV3SsPYU+NLj/PUt9vXsPHUYe12Rx6T+2AverdPMcG2eHA4e2RnCdcC0jbZPg9ymVQ3tMj/hJOetbyTJugMpaWeKpEnEime63kUuTeQrE9w5qZ0G2cmjPp4i7U7BPBQjeIldARtxa2tTtCkKmCIph855O3C5VxkLJ1jshCcXHLYoiw5IL2lxwmzk4Nvo/zWJRPCZHV6VjfkcX5bN8E4GwvSQB0KJbwUD7z3SRr1nPbOfCZnSIZKkZydYamD9mLDRItiOEy7EaPKnhb4gP/OCU8s+7g7V2Ld2ND8m7llXvxdgblc89wy9BIM1xkaIyXVPhTIjq/Sc1gB6q2ERyBjL3OSC3J91iAvOzWVzuWcxw+QKXTtfJ+8qAQh5NcV6qRnQKhsKSVjb2LzDM4WyO6fBmoRbPVtIbjqdujjWqal/Gk5V45DpNHNk2v8iQKMR05bJcUoDfUh8RYwL7cZZGAVIbKmdFO2CbhJ7nbm/oU0=
  email: misterjt@mail.ru
  provider: npm
